---
extends:
  - stylelint-config-standard-scss
  - stylelint-config-rational-order
plugins:
  - stylelint-scss
  - stylelint-order
rules:
  declaration-empty-line-before: null
  plugin/rational-order:
    - true
    - empty-line-between-groups: true
  at-rule-no-unknown: null
  at-rule-empty-line-before: null
  scss/at-rule-no-unknown: true
  scss/dollar-variable-empty-line-before: null
  scss/no-global-function-names: null
ignoreFiles:
  - '**/*.vue'
  - '**/*.js'
